# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a152d7ba824d9dd441e4b10984033f403afd75ac1639ac6bd8e44464d4fe180926d53090f6e2ac50a40938909486003b29112d36173bb6d039a8330ff521e37d

test:
  secret_key_base: a15ede148f5404f16cf4d6c55c91da4fed45b40b217fb90465ec0ccd7b0932bde94489a79aa1da193c4ea4b8f52f2f95d879cb9eb6b082d3c31012858e8ad324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
