# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12251ba2fb164da16549f5921efc63b2028b35341b9bcc80a2d50c03f9c9333e064d02fca0f09fad5891d87931bde3da6bec9f87d344fc17b2908fcb7b9856b6

test:
  secret_key_base: f47a047dcc86daf40ef549fedccb200291c2eb870f22ad47f69d201c3a823b74e77fc90671766ac5a8cbee30122ab3e55e01087fe1eb60f21767f918c579005e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
